### ISSUE TITLE
Run on Raspberry pi

### ISSUE THREAD

**Issue by andrychuyko** [saljut7/seafile-client-rpi#1]
It need install 
sudo apt-get install qt5-default libqtcore4

**Comment by saljut7** [comment]
Hi @andrychuyko 

thanks alot for reporting this. I remember these dependencies and added it to the tutorial now: 

https://github.com/saljut7/seafile-client-rpi/blob/master/README.md

For some reason I have problems to compile the newest (6.0.1) client. Will buy a dedicated RPi for compiling soon and hope I can update the packages then. 

Best regards
sj7
